### ISSUE TITLE
RealtimeMutatable::nonRealtimeAcquire loops indefinitely

### ISSUE THREAD

**Issue by reuk** [hogliux/farbot#3]
https://github.com/hogliux/farbot/blob/66c46cdf819b81f7676daa60adfd1e7706d24b5c/RealtimeMutatable.tcc#L48

It looks to me like realtimeRelease toggles the BUSY_BIT on, which means that subsequent calls to `nonRealtimeAcquire` will loop for ever, waiting for the busy bit to become unset.

I'm not convinced that the realtimeAcquire is correct either, shouldn't it set the busy bit?

**Comment by seece** [comment]
This looks like a bug to me too. You can see the code on the slides of [the ADC19 talk](https://youtu.be/PoZAo2Vikbo?list=PLe2skUvADfhvu_pyet1veIIEAH0LA4iFK&t=875) doesn't have `BUSY_BIT` set since `(i & BIT_IDX)` clears it.

![image](https://user-images.githubusercontent.com/934568/71769669-871b4800-2f2c-11ea-99f7-6586575e3492.png)

**Comment by vassilisw** [comment]
Any updates on this?

**Comment by hogliux** [comment]
This was fixed with commit 9004a0d
